M48
; DRILL file KiCad 10.0.5 date 2026-07-24T20:45:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-24T20:45:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X44.18Y-69.0
T2
X52.69Y-85.0
X107.93Y-69.0
M30
